### ISSUE TITLE
gpg signature failed while checking

### ISSUE THREAD

**Issue by JuanjoCatala** [puxplaying/linux-gc-fsync#1]
My terminal is in spanish

==> Validando los archivos source con sha256sums...
    linux-5.7.10.tar.xz ... Aprobado
    linux-5.7.10.tar.sign ... Omitido
    config ... Aprobado
    0000-sphinx-workaround.patch ... Aprobado
    0001-futex-patches.patch ... Aprobado
    0002-fsgsbase-patches.patch ... Aprobado
    0003-syscall-user-dispatch.patch ... Aprobado
    prjc_v5.7-r2.patch ... Aprobado
    enable_additional_cpu_optimizations-20200615.tar.gz ... Aprobado
    0004-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-C.patch ... Aprobado
    0005-PCI-EDR-Log-only-ACPI_NOTIFY_DISCONNECT_RECOVER-even.patch ... Aprobado
    0006-iwlwifi-Make-some-Killer-Wireless-AC-1550-cards-work.patch ... Aprobado
    0007-virt-vbox-Add-support-for-the-new-VBG_IOCTL_ACQUIRE_.patch ... Aprobado
    Fix-compilation-issues-when-CONFIG-SCHED-TRACER.patch ... Aprobado
==> Verificando las firmas de las fuentes con gpg...
    linux-5.7.10.tar ... HA FALLADO (clave pública desconocida 38DBBDC86092693E)
==> ERROR: ¡No se ha podido verificar alguna de las firmas PGP!

**Comment by puxplaying** [comment]
Hi i can't reproduce the checksum error, please run `updpkgsums` to update the PKGBUILD and try again with `makepkg -srci`.

**Comment by JuanjoCatala** [comment]
It is still giving me the same error. Sorry for sending you the error in spanish and thanks for your reply xd



[juanjo@arch linux-gc-fsync]$ updpkgsums
==> Recibiendo las fuentes...
  -> linux-5.7.10.tar.xz ha sido encontrado 
  -> linux-5.7.10.tar.sign ha sido encontrado 
  -> config ha sido encontrado 
  -> 0000-sphinx-workaround.patch ha sido encontrado 
  -> 0001-futex-patches.patch ha sido encontrado 
  -> 0002-fsgsbase-patches.patch ha sido encontrado 
  -> 0003-syscall-user-dispatch.patch ha sido encontrado 
  -> prjc_v5.7-r2.patch ha sido encontrado 
  -> enable_additional_cpu_optimizations-20200615.tar.gz ha sido encontrado 
  -> 0004-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-C.patch ha sido encontrado 
  -> 0005-PCI-EDR-Log-only-ACPI_NOTIFY_DISCONNECT_RECOVER-even.patch ha sido encontrado 
  -> 0006-iwlwifi-Make-some-Killer-Wireless-AC-1550-cards-work.patch ha sido encontrado 
  -> 0007-virt-vbox-Add-support-for-the-new-VBG_IOCTL_ACQUIRE_.patch ha sido encontrado 
  -> Fix-compilation-issues-when-CONFIG-SCHED-TRACER.patch ha sido encontrado 
==> Generando las sumas de control para los archivos fuentes...
[juanjo@arch linux-gc-fsync]$ makepkg -srci
==> Creando el paquete: linux-gc 5.7.10-1 (sáb 25 jul 2020 00:05:24)
==> Comprobando dependencias mientras se ejecuta...
==> Comprobando dependencias mientras se compila...
==> Recibiendo las fuentes...
  -> linux-5.7.10.tar.xz ha sido encontrado 
  -> linux-5.7.10.tar.sign ha sido encontrado 
  -> config ha sido encontrado 
  -> 0000-sphinx-workaround.patch ha sido encontrado 
  -> 0001-futex-patches.patch ha sido encontrado 
  -> 0002-fsgsbase-patches.patch ha sido encontrado 
  -> 0003-syscall-user-dispatch.patch ha sido encontrado 
  -> prjc_v5.7-r2.patch ha sido encontrado 
  -> enable_additional_cpu_optimizations-20200615.tar.gz ha sido encontrado 
  -> 0004-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-C.patch ha sido encontrado 
  -> 0005-PCI-EDR-Log-only-ACPI_NOTIFY_DISCONNECT_RECOVER-even.patch ha sido encontrado 
  -> 0006-iwlwifi-Make-some-Killer-Wireless-AC-1550-cards-work.patch ha sido encontrado 
  -> 0007-virt-vbox-Add-support-for-the-new-VBG_IOCTL_ACQUIRE_.patch ha sido encontrado 
  -> Fix-compilation-issues-when-CONFIG-SCHED-TRACER.patch ha sido encontrado 
==> Validando los archivos source con sha256sums...
    linux-5.7.10.tar.xz ... Aprobado
    linux-5.7.10.tar.sign ... Omitido
    config ... Aprobado
    0000-sphinx-workaround.patch ... Aprobado
    0001-futex-patches.patch ... Aprobado
    0002-fsgsbase-patches.patch ... Aprobado
    0003-syscall-user-dispatch.patch ... Aprobado
    prjc_v5.7-r2.patch ... Aprobado
    enable_additional_cpu_optimizations-20200615.tar.gz ... Aprobado
    0004-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-C.patch ... Aprobado
    0005-PCI-EDR-Log-only-ACPI_NOTIFY_DISCONNECT_RECOVER-even.patch ... Aprobado
    0006-iwlwifi-Make-some-Killer-Wireless-AC-1550-cards-work.patch ... Aprobado
    0007-virt-vbox-Add-support-for-the-new-VBG_IOCTL_ACQUIRE_.patch ... Aprobado
    Fix-compilation-issues-when-CONFIG-SCHED-TRACER.patch ... Aprobado
==> Verificando las firmas de las fuentes con gpg...
    linux-5.7.10.tar ... HA FALLADO (clave pública desconocida 38DBBDC86092693E)
==> ERROR: ¡No se ha podido verificar alguna de las firmas PGP!

**Comment by puxplaying** [comment]
It seems that you need to sign the gpg key, please try `gpg --keyserver pgp.mit.edu --recv-keys 38DBBDC86092693E`
